### ISSUE TITLE
yarn页面显示无法访问

### ISSUE THREAD

**Issue by Hurricane672** [PKC278/docker_hadoop#1]
访问localhost:8088之后显示无法访问，有时会跳转到slave1:8088，应该如何处理

**Comment by PKC278** [comment]
你修改docker-compose文件，把slave1也映射一个端口，直接访问slave1的端口

**Comment by Hurricane672** [comment]
slave1和master的yarn没有区别吗

**Comment by Hurricane672** [comment]
另外运行示例程序pi的时候报错如下，啥情况
<img width="713" alt="image" src="https://github.com/PKC278/docker_hadoop/assets/26060756/a4fadd4a-d832-424e-b081-78c21a3e8d21">

**Comment by PKC278** [comment]
> 另外运行示例程序pi的时候报错如下，啥情况
> 
> <img width="713" alt="image" src="https://github.com/PKC278/docker_hadoop/assets/26060756/a4fadd4a-d832-424e-b081-78c21a3e8d21">
> 
> 

我也遇到了这个问题，好像是因为端口被占用，我在我的电脑运行没有问题，我的电脑是mac m2，在其他x86架构电脑运行也会报和你差不多的错误，我现在正在研究

**Comment by Hurricane672** [comment]
> > 另外运行示例程序pi的时候报错如下，啥情况
> > <img alt="image" width="713" src="https://user-images.githubusercontent.com/26060756/238534400-a4fadd4a-d832-424e-b081-78c21a3e8d21.png">
> 
> 我也遇到了这个问题，好像是因为端口被占用，我在我的电脑运行没有问题，我的电脑是mac m2，在其他x86架构电脑运行也会报和你差不多的错误，我现在正在研究

我电脑是mac air m1，最近需要做一个hadoop的项目，我也研究研究，有进展随时沟通

**Comment by PKC278** [comment]
我又在nas上和两个同学的电脑进行了测试，nas和一个同学的电脑正常，另外一个同学运行报错，和架构应该没关系，可能和内存有关

**Comment by Hurricane672** [comment]
哈哈哈 我到最后也没成功 可能是电脑问题 不管了
