### ISSUE TITLE
无法在idea执行代码

### ISSUE THREAD

**Issue by Alexaenr** [PKC278/docker_hadoop#5]
无法在idea执行代码
public class HdfsClient {

    private FileSystem fs;

    @Before
    public void init() throws URISyntaxException, IOException, InterruptedException {
        //连接集群的地址
        URI uri = new URI("hdfs://localhost:8020");
        //创建一个配置文件
        Configuration configuration = new Configuration();

        configuration.set("dfs.replication","2");
        //用户
        String user = "root";

        //1、获取到了客户端对象
        fs = FileSystem.get(uri,configuration,user);

    }

    @After
    public void close() throws IOException {
        //3、关闭资源
        fs.close();
    }

    //创建目录
    @Test
    public void testMkdir() throws IOException {
        //2、执行相关的操作命令
        fs.mkdirs(new Path("/demo"));
    }

    //重命名目录
    @Test
    public void testRenameDir() throws IOException {
        //2、执行相关的操作命令
        fs.rename(new Path("/demo"),new Path("/demo3"));
    }

    //删除目录
    @Test
    public void testRmdir() throws IOException {
        //2、执行相关的操作命令
        fs.delete(new Path("/demo3"),true);
    }

    //上传文件
    @Test
    public void testPutFile() throws IOException {
        //2、执行相关的操作命令
        fs.copyFromLocalFile(new Path("src/main/java/hdfs/demo.txt"),new Path("/demo"));
    }

    //文件下载
    @Test
    public void testGetFile() throws IOException {
        //2、执行相关的操作命令
        fs.copyToLocalFile(new Path("/demo/demo.txt"),new Path("/root/demo1.txt"));
    }

    //删除
    @Test
    public void testRm () throws IOException {
        //参数1：要删除的文件路径  参数2：是否递归删除
        fs.delete(new Path("/demo"),true);
    }

    //文件的更名和移动
    @Test
    public void testRename() throws IOException {
        //参数1：原文件路径，参数2：目标文件路径
        fs.rename(new Path("/demo1"),new Path("/demo2"));
    }

    //获取文件详细信息
    @Test
    public void fileDetail() throws IOException {
        //获取文件所有信息
        RemoteIterator<LocatedFileStatus> listFiles = fs.listFiles(new Path("/"),true);

        //遍历文件
        while (listFiles.hasNext()) {
            LocatedFileStatus fileStatus = listFiles.next();
            System.out.println("======" + fileStatus.getPath() + "=====");
            System.out.println(fileStatus.getPermission());
            System.out.println(fileStatus.getOwner());
            System.out.println(fileStatus.getGroup());
            System.out.println(fileStatus.getLen());
            System.out.println(fileStatus.getModificationTime());
            System.out.println(fileStatus.getReplication());
            System.out.println(fileStatus.getBlockSize());
            System.out.println(fileStatus.getPath().getName());
            //获取存储的块信息
            BlockLocation[] blockLocations = fileStatus.getBlockLocations();
            System.out.println(Arrays.toString(blockLocations));
        }
    }

    //判断是文件夹还是文件
    @Test
    public void testFile() throws IOException {
        FileStatus[] fileStatuses = fs.listStatus(new Path("/"));
        for (FileStatus fileStatus : fileStatuses) {
            if(fileStatus.isFile()){
                System.out.println("f:"+fileStatus.getPath().getName());
            }else{
                System.out.println("d:"+fileStatus.getPath().getName());
            }
        }
    }
}
尝试过在容器中运行

![微信图片_20240227120116](https://github.com/PKC278/docker_hadoop/assets/161349777/c0940f0e-ff43-4399-851a-835866031da3)
[
![微信图片_20240227120121](https://github.com/PKC278/docker_hadoop/assets/161349777/6ddc281d-0832-494a-93c6-9cf62aaefcd4)
](url)
![微信图片_20240227120124](https://github.com/PKC278/docker_hadoop/assets/161349777/f9698025-aeb8-420b-83a4-8dfa57f47ac2)
一直卡在这儿了，无法继续执行

**Comment by PKC278** [comment]
最后上传的这个文件是很大的文件吗，还是一个文件夹，如果零散文件特别多的话，由于windows没有安装rsync的话ssh上传会很慢

**Comment by Alexaenr** [comment]
wsl中的ubuntu有rsync，win本地上我也装了一个，但还是无法执行，一直卡在那儿（创建目录的测试方法也无法执行）
![微信图片_20240227132810](https://github.com/PKC278/docker_hadoop/assets/161349777/6d06a3ba-ec30-4663-8042-94300b6485e8)

**Comment by Alexaenr** [comment]
博主，您要是方便的话，可以抽个时间弄个腾讯会议帮我看一下不，联系方式qq: 1341603860

**Comment by PKC278** [comment]
单独新建一个项目试试，我最近1个月没大有时间

**Comment by Alexaenr** [comment]
不行啊，试过好几次了，真的不知道该咋整的

**Comment by PKC278** [comment]
通过ssh的scp命令手动上传一个文件试试

**Comment by Alexaenr** [comment]
最近找问了几个我们学校的老师，老师都没用过docker。身边的同学也没使用docker的，自己折腾了好久也不知道该咋弄，目前不是很慌，我再等等吧，等您时间方便的时候帮我看一下

**Comment by Alexaenr** [comment]
最近问了几个我们学校的老师，老师都没用过docker。身边的同学也没使用docker的，自己折腾了好久也不知道该咋弄，目前不是很慌，我再等等吧，等您时间方便的时候帮我看一下

**Comment by PKC278** [comment]
抱歉这个事情搁置了许久，如果还需要帮忙的话，发联系方式到我的邮箱吧 ```stops_rubs_1f@icloud.com```
